Add index.html and style.css
riskmaris/hello-microverse pull request #1
Opened 2023-03-21 19:19 UTC by riskmaris

2023-03-21 21:34 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @riskmaris, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-21 21:34 UTC, Qoosim commented on README.md
> +> Describe your project in 1 or 2 sentences.
- [ ] This is an instruction telling your what you're expected to do. You're expected to replace this placeholder text with the appropriate response. Kindly look into it and fix it too.

2023-03-21 21:34 UTC, Qoosim commented on README.md
> +
- [ ] Same thing goes here too. Kindly replace the appropriate response to the placeholder text.

2023-03-21 21:34 UTC, Qoosim commented on README.md
> +
- [ ] You're required to give at least one key feature under this heading and remove the placeholder text `Describe between 1-3 key features of the application.`

2023-03-21 21:34 UTC, Qoosim commented on README.md
> +
- [ ] It is allowed to write `N/A` under any heading that's not related to your project. But ensure all the headings from the Microverse template present in your README file except `FAQ` which is optional. Kindly fix this.

2023-03-21 21:34 UTC, Qoosim commented on README.md
> +
- [ ] Kindly follow all the instructions under each headings and write `N/A yet` under any one that's not related to your project.

2023-03-21 21:34 UTC, Qoosim commented on README.md
> +
- [ ] Kindly remove one author and replace all the social media handles with your respective ones.

2023-03-21 21:34 UTC, Qoosim commented on README.md
> +
- [ ] You're required to give at least one future feature under this heading and remove the placeholder text `Describe between 1-3 features of the application.`

2023-03-21 21:34 UTC, Qoosim commented on README.md
> +> Write a message to encourage readers to support your project
- [ ] Kindly remove this

2023-03-21 21:34 UTC, Qoosim commented on README.md
> +> Give credit to everyone who inspired your codebase.
- [ ] Kindly remove this too and give your acknoledgements to whoever deserves it.

2023-03-21 21:34 UTC, Qoosim commented on README.md
> +
- [ ] Kindly provide the appropriate questions and answers or remove the `FAQ` completely as it is optional to remain in your README file.

2023-03-21 21:34 UTC, Qoosim commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] The link to the MIT License is broken at this moment. Kindly follow this [link](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to set ip up properly for your project.

![license](https://user-images.githubusercontent.com/26597432/226746314-7d5d51ef-069a-446a-9963-d242492d65cd.png)

2023-03-21 21:34 UTC, Qoosim commented on README.md
> +
- [ ] Kindly remove this. It is not necessary to be there

2023-03-22 19:05 UTC, TuyishimireEric requested changes
# Status: REQUIRED CHANGES :recycle: 
### Hi  @riskmaris  👋 👋 
#### I'm @TuyishimireEric, Your code reviewer,
Good job so far! 🥇 
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)
## Highlight 
✔ Used correct GitFlow👍 
✔ No Linter Errors 👍 

## Required Changes ♻️

- [ ]  Check the comments below 

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 12:08 UTC, AbelG101 approved these changes
![](https://media.giphy.com/media/eKfovWZOlOpbTDEX9F/giphy.gif)

## Hi @riskmaris 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 

## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔

## Optional suggestions
- **[OPTIONAL] As mentioned by the previous reviewer it's not professional to leave the PR description empty as this is where you should provide a well-detailed summary of what you've achieved in this specific milestone 🎯. So please make those improvements in your next project. 👍**
- **[OPTIONAL] Once again As mentioned by the previous reviewer your branch name should be the name of a feature you've added so kindly fix that as well. you can call it for example `basic-structure`**
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 12:12 UTC, merged