First project
riskmaris/hello-microverse pull request #1
Opened 2023-05-30 14:38 UTC by riskmaris

- Create HTML and CSS files
- Add linters
- Add README file
-

2023-05-30 16:01 UTC, skyv26 requested changes
## Hi @riskmaris, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/3o7aCPbznb29hgOgG4/giphy.gif)

## Highlights
- Correct `Linters` configuration ✅ 
- Correct `GitHub` flow ✅ 
- Linters are passing ✅ 

## Required Changes ♻️
- [ ] Please 🙏🏻 🙏🏻  don't open a new pull request for the review next time, as it makes the things difficult to make track of the review. Kindly follow the things appropriately.

- [ ] Kindly write a meaningful PR title for your pull request, because I can see your PR title is long and not seems to be meaningful as per the project feature implemented.

<table>
<tr>
<th align=“middle”>Your PR title</th>
<th align=“middle”>Professional PR title</th>
</tr>
<tr>
<td>

![Screenshot from 2023-05-30 21-23-16](https://github.com/riskmaris/hello-microverse/assets/66476329/5dce2a7d-de59-40e1-85e2-15233e056d97)

</td>
<td>

![Screenshot from 2023-05-30 19-28-25](https://github.com/Afsheen96/Hello-Microverse/assets/66476329/417ad62e-82d4-41a9-9163-235b8bdab6e7)

</td>
</tr>
</table>

- [ ] Please try to write a descriptive PR as I can see that your PR description is empty which is not professional at all, having a descriptive PR will help any person to understand your project feature implementation detail.

<table>
<tr>
<th align=“middle”>Your PR description</th>
<th align=“middle”>Professional PR description</th>
</tr>
<tr>
<td>

![image](https://github.com/riskmaris/hello-microverse/assets/66476329/2e25fa8e-1e78-40fb-89b7-1b8dff44c5eb)

</td>
<td>

![Screenshot from 2023-04-28 21-07-13](https://github.com/Arch-Noize/microverse-hello-world/assets/66476329/33e5c201-413f-496f-b4f8-21dc46906413)

</td>
</tr>
</table>

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag @skyv26 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 16:01 UTC, skyv26 commented on style.css
> +header {
- [ ] Please adhere to the `project requirement` because it will help you in future for example you got work from a client and the client sent the requirements and you implemented something `against` his/her requirement then the service you provided to your client can be considered as the *Bad User Experience* because adding your creativity as the developer is a very good thing but there will be no guarantee that your client will like it. I hope you understand this example.
- [ ] Kindly look at the image attached below


![Screenshot from 2023-04-26 21-33-36](https://user-images.githubusercontent.com/66476329/234634620-315d1ba8-d4d3-4d8e-b2bc-e53ae768501f.png)

- So please make sure that you need to add a *class* for your `h1` tag inside the `index.html` file.

**NOTE: Always try to add your creativity after fulfilling the project requirement.**

2023-05-30 16:01 UTC, skyv26 commented on LICENSE.txt
> +WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
- [ ] Please customize this `LICENSE` with your relevant information. It seems like you are using someone's LICENSE which is *OK* at first glance but professionally it is not good. Please be a professional developer and try to customize it.

2023-05-30 16:01 UTC, skyv26 commented on .gitignore
> +node_modules
- [ ] Please follow the project requirement carefully, according to which your `test.md` file should be ignored by the `.gitignore` file. As I can see very well you added the `test.md` file into the `gitignore` but you did add the file after adding the `test.md` file on staging. So kindly remove the `test.md` file and make a commit and then try to add the file again and it will automatically be ignored by the *gitignore.*

### Project Requirements

![Screenshot from 2023-04-25 16-59-11](https://github.com/Arch-Noize/microverse-hello-world/assets/66476329/f9f93ae0-4be9-41b2-a014-c3970febbdbd)

2023-05-30 16:01 UTC, skyv26 commented on README.md
> +<h3><b>Microverse README Template</b></h3>
- [ ] Please remove this text from your `README`, it makes your documentation unprofessional.

2023-05-31 07:51 UTC, closed without merging

2023-05-31 08:04 UTC, riskmaris commented
Hello @skyv26 
Am sorry i made a mistake and closed my branch (First project) as I was trying to make the changes you requested me to.
Please can you advise me on what to do?

2023-05-31 08:21 UTC, skyv26 commented
@riskmaris please mention this [PR](https://github.com/riskmaris/hello-microverse/pull/1) link in your new branch pull request inside the description it will help the code reviewer to understand the issue because you have closed this branch that's why.